services:
#database section

    #TourDB: sql server
    tourdb:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: tourdb
        environment:
            SA_PASSWORD: "Passw0rd!"
            ACCEPT_EULA: "Y"
        restart: always
        volumes:
            - /var/lib/mssql/data
        ports:
            - "1435:1433"

    #TourCache: Redis
    tourcache:
          image: redis:alpine
          container_name: tourcache
          restart: always
          ports: 
            - "6380:6379"

    #TourSearchDB: mongodb
    toursearchdb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=mongopw
        container_name: toursearchdb
        restart: always
        ports:
            - "27018:27017"
        volumes:
            - /var/lib/mongodb/data

    #IdentityServerDB: postgres
    identitydb:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgrespw
        container_name: identitydb
        restart: always
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postresql/data

#infrastructure section
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - /var/lib/rabbitmq/data
        hostname: rabbitmq

#network section
networks:
    default:
        name: tour_ease
        driver: bridge

#volumes section
# volumes:
#     sqlserver_data:
#         name: sqlserver_data
#     mongo_data:
#         name: mongo_data
#     rabbitmq_data:
#         name: rabbitmq_data